### PR TITLE
Handle connection strings from multiple related MongoDB hosts

### PR DESCRIPTION
**Pull request by tkuhlman**
While working on a new Graylog charm (https://launchpad.net/graylog-charm) I discovered that for a clustered MongoDB setup I need to know all of the ips. I modified the interface to return this data.

This is a breaking change and I'm not sure how you want to handle that. For now I have created another entry for it at http://interfaces.juju.solutions/interface/mongodb-cluster/

### CODE REVIEW

**Comment by mattyw** [comment]
@tkuhlman the code itself seems reasonable, but isn't it normally the case that most mongo clients should connect with a single hostname, and then discover the arrangement of the cluster from that single connection? It's certainly the case with mgo and pymongo

**Comment by tkuhlman** [comment]
@mattyw What happens if the one hostname being used in the machine that happens to be down? I am using the multiple hosts to construct the MongoDB URI as described here, https://docs.mongodb.com/manual/reference/connection-string/
I'm not expert on what other systems require but that link from the MongoDB documentation at least suggests multiple hosts in the connection string is expected.

**Comment by tkuhlman** [comment]
I looked at pymongo a bit and it seems it also supports multiple hosts in the connection string. This appears to be required for load balancing across the cluster, http://api.mongodb.com/python/current/examples/high_availability.html?highlight=cluster#mongos-load-balancing

**Comment by mattyw** [comment]
@tkuhlman I'm not too familiar with pymongo, and I'm not sure what is meant by load balancing in this context, as all writes would only go to master anyway. I'm guessing it's useful when sharding, but the docs doesn't specify this clearly.
With the present state of the mongo charm there can be issues with relying on a multi host connection string as it's currently possible for the charm to be deployed with 2 replicasets in a single application (https://git.launchpad.net/mongodb-charm/tree/README.md#n48). Which is one of the reasons we decided to go with just one hostname (since most drivers detect the other hosts in the replicaset automatically. Indeed, the connection string is just a guide to work out the shape of the replicaset, as this may change at any moment.

Nevertheless there are indeed situations when a multi host string would be useful (it looks like the java mongodb library used by gray log doesn't do the auto detection that pymongo and mgo do).

I think I'd prefer this behaviour to exist alongside the existing behaviour rather than maintain a branched interface with basically the same functionality. Would it be possible for you to add the new connection_strings function alongside existing functionality? That way all possibilities should be catered for?

And thanks for bearing with me while I work all this out :)

**Comment by tkuhlman** [comment]
Unfortunately I don't think I can rework this to allow for both sets of functionality because of the scope change from global to unit. The scope change is required for returning all of the units but it breaks the auto_accessors. If the code here is the only thing using the auto_accessors then I could add back in a connection_string method and leave the scope as unit. Do you think it is okay to remove the auto_accessors?

**Pull request closed without merging**
